### ISSUE TITLE
Quick search feature in readthedocs shows results with broken links

### ISSUE THREAD

**Issue by jeverling** [robinhood/faust#126]
When I use the *Quick Search* feature in the documentation, the links of the search results are not working. For example, when I search for `celery`, the first result will link to http://fauststream.com/en/latest/playbooks/vscelery.html?highlight=celery instead of http://faust.readthedocs.io/en/latest/playbooks/vscelery.html.
The fauststream.com link will redirect to the readthedocs.org homepage.

**Comment by ask** [comment]
Thanks! Documentation should build shortly and it should be fixed on faust.readthedocs.io soon

**Comment by erip** [comment]
This still isn't fixed. See [here](https://faust.readthedocs.io/en/latest/search.html?q=service&check_keywords=yes&area=default).
