### ISSUE TITLE
Heartbeat failed and hang

### ISSUE THREAD

**Issue by DeoLeung** [robinhood/faust#259]
## Checklist

- [x] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

it works for a while and suddenly hangs

## Expected behavior

don't hang

## Actual behavior

I have the worker using threads to call pytesseract, one worker 20 threads (actually it will use 20 subprocess) maybe this is the cause of the hanging.

## Full traceback
```bash
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:11:35,433: WARNING]: Heartbeat failed for group internal_text_recognize because it is rebalancing
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:11:35,433: INFO]: Revoking previously assigned partitions frozenset({TopicPartition(topic='internal_text_recognize-__assignor-__leader', partition=0), TopicPartition(topic='interna
l_text_recognize', partition=0)}) for group internal_text_recognize
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:11:38,432: WARNING]: Heartbeat failed for group internal_text_recognize because it is rebalancing
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:11:41,466: WARNING]: Heartbeat failed for group internal_text_recognize because it is rebalancing
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:11:44,431: WARNING]: Heartbeat failed for group internal_text_recognize because it is rebalancing
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:11:47,430: WARNING]: Heartbeat failed for group internal_text_recognize because it is rebalancing
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:11:50,431: WARNING]: Heartbeat failed for group internal_text_recognize because it is rebalancing
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:12:32,507: WARNING]: [^-App]: Warning: Task timed out!
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:12:32,507: WARNING]: [^-App]: Please make sure it is hanging before restarting.
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:12:32,507: INFO]: [^-App]: [Flight Recorder-17] (started at Wed Jan  2 18:11:35 2019) Replaying logs...
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:12:32,507: INFO]: [^-App]: [Flight Recorder-17] (Wed Jan  2 18:11:35 2019) flow_control.suspend()
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:12:32,508: INFO]: [^-App]: [Flight Recorder-17] (Wed Jan  2 18:11:35 2019) consumer.pause_partitions
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:12:32,508: INFO]: [^-App]: [Flight Recorder-17] (Wed Jan  2 18:11:35 2019) flow_control.clear()
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:12:32,508: INFO]: [^-App]: [Flight Recorder-17] (Wed Jan  2 18:11:35 2019) consumer.wait_empty()
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:12:32,508: INFO]: [^-App]: [Flight Recorder-17] -End of log-
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:13:33,138: WARNING]: Marking the coordinator dead (node 1001)for group internal_text_recognize.
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:13:34,638: INFO]: Discovered coordinator 1001 for group internal_text_recognize
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:13:34,639: WARNING]: Heartbeat failed: local member_id was not recognized; resetting and re-joining group
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:13:34,639: ERROR]: Heartbeat session expired - marking coordinator dead
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:13:34,639: WARNING]: Marking the coordinator dead (node 1001)for group internal_text_recognize.
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:13:36,140: INFO]: Discovered coordinator 1001 for group internal_text_recognize
ESC[36mrisk-pytesseract_1          |ESC[0m [2019-01-02 18:13:36,141: WARNING]: Heartbeat failed: local member_id was not recognized; resetting and re-joining group
```
and early time I found this as well
```bash
risk-pytesseract_1          | [2019-01-02 14:03:07,317: WARNING]: Marking the coordinator dead (node 1001)for group internal_text_recognize.
risk-pytesseract_1          | [2019-01-02 14:03:08,698: WARNING]: [^--Consumer]: Possible livelock: COMMIT OFFSET NOT ADVANCING
risk-pytesseract_1          | [2019-01-02 14:03:08,817: INFO]: Discovered coordinator 1001 for group internal_text_recognize
risk-pytesseract_1          | [2019-01-02 14:03:08,818: WARNING]: Heartbeat failed: local member_id was not recognized; resetting and re-joining group
risk-pytesseract_1          | [2019-01-02 14:03:08,818: ERROR]: Heartbeat session expired - marking coordinator dead
risk-pytesseract_1          | [2019-01-02 14:03:08,818: WARNING]: Marking the coordinator dead (node 1001)for group internal_text_recognize.
risk-pytesseract_1          | [2019-01-02 14:03:10,318: INFO]: Discovered coordinator 1001 for group internal_text_recognize
risk-pytesseract_1          | [2019-01-02 14:03:10,319: WARNING]: Heartbeat failed: local member_id was not recognized; resetting and re-joining group
risk-pytesseract_1          | [2019-01-02 14:03:10,319: ERROR]: Heartbeat session expired - marking coordinator dead
risk-pytesseract_1          | [2019-01-02 14:03:10,319: WARNING]: Marking the coordinator dead (node 1001)for group internal_text_recognize.
risk-pytesseract_1          | [2019-01-02 14:03:11,820: INFO]: Discovered coordinator 1001 for group internal_text_recognize
```

# Versions

* Python version: 3.6.7
* Faust version: 1.4.2
* Operating system: debian strench
* Kafka version: 2.1.1
* RocksDB version (if applicable)

**Comment by mstump** [comment]
We're seeing something similar where a node gets into a "death spiral" emitting warning/error messages several times per second. The only way to resolve the issue is to reboot the node. We often see it when doing a rolling restart due to a new deployment, although not exclusively. Nodes will sometimes spontaneously jump to this state after being OK for several minutes or hours. We thought that maybe it has something to do with our large message sizes (4.6MB) but not certain. The team also wonders whether it might be a bug fixed in upstream aiokafka but I haven't seen a specific fix yet.

```
[2019-01-02 22:53:08,402: WARNING]: Heartbeat failed: local member_id was not recognized; resetting and re-joining group

times ~100

[2019-01-02 22:53:13,005: WARNING]: Marking the coordinator dead (node 2)for group pipeline.
[2019-01-02 22:53:13,238: INFO]: Discovered coordinator 2 for group pipeline
[2019-01-02 22:53:13,240: WARNING]: Heartbeat failed: local member_id was not recognized; resetting and re-joining group
[2019-01-02 22:53:13,240: ERROR]: Heartbeat session expired - marking coordinator dead
 
then we will see these pretty much until the pod is restarted.
```

**Comment by mstump** [comment]
@DeoLeung we saw stability increase after turning off concurrency. You may want to try that.

**Comment by warmwaffles** [comment]
We also turned down the replica count to 1 and it seems to work just fine. Very concerning that it doesn't scale horizontally well.

**Comment by DeoLeung** [comment]
yes, currently we set concurrency to 1 and use multiple worker with multiple partition, seems to be ok at the moment, also we handle an unnoticed Exception from `pytesseract`, which may be the cause of the hanging

**Comment by etos** [comment]
same issue, but concurrency=1 does not fix the issue

version 1.4.5

**Comment by macdoor** [comment]
concurrency=1 does not fix the issue

version 1.4.6

**Comment by barelyreal** [comment]
I've also been having this problem, and it seems like it's exacerbated by longer-running worker processing, and more worker instances.  The longer my workers take to process a message (or messages, using take) without yielding, the more likely it seems for this problem to occur.

**Comment by barelyreal** [comment]
Has anyone found any workarounds or ways to mitigate this?  It appears to be a somewhat recent problem as I don't recall seeing it a few months ago.  I've tried rolling back to older versions of faust to no avail, perhaps it has something to do with the version of aiokafka?  As it is, this is seriously impacting the stability of my system.

**Comment by mstump** [comment]
I asked some people on my team to followup providing information but we tracked it back an accumulation of promises within Faust (essentially a resource leak), that results in an eventual GC storm. We migrated off to our own home-grown thing.

**Comment by ask** [comment]
I think I have fixed this issue in 1.4.7

**Comment by barelyreal** [comment]
Unfortunately I'm still seeing this in 1.4.7, it just doesn't happen as often now.  Here's an example log of this in action.
[faust-deadlock.txt](https://github.com/robinhood/faust/files/2987585/faust-deadlock.txt)

**Comment by heron182** [comment]
Confirm that the problem persist.
From my testing the message `Heartbeat failed for group x because it is rebalancin` is from `aiokafka`.

I made another test using only the new version of `aiokakfa`(without faust) and it worked.
Robinhood repo has a old version of `aiokafka` forked so maybe that's related ?

**Comment by mamoit** [comment]
Maybe it has something to do with [this](https://github.com/aio-libs/aiokafka/pull/472/commits/4d5dfea99a75ced7591ea44630f4fb2a535b5724)?

**Comment by mamoit** [comment]
Can this issue be related to the fact that the default session_timeout > request_timeout as stated [here](https://github.com/dpkp/kafka-python/issues/739#issuecomment-279417868)?
In faust's case the defaults are 60 > 40
