### ISSUE TITLE
Stream.filter doesn't ack filtered events

### ISSUE THREAD

**Issue by martinmaillard** [robinhood/faust#391]
I'm not sure if this is a bug or a misunderstanding on my part, but I noticed that `Stream.filter` doesn't "ack" filtered events. It causes issues when chaining `filter` with `take`. The specific issue I noticed is that my app hangs forever when trying to stop it, but I suspect that it's not the only one.

## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

With the following agent code:
```python
@app.agent(test_topic)
async def my_agent(stream):
    async for batch in stream.filter(lambda e: False).take(3, within=20):
        print(f'Handle batch: {batch}')
``` 

If I try to stop the process with ^C (SIGINT), it hangs forever:
```
[2019-07-29 16:48:04,888: WARNING]: [^--Consumer]: wait_empty: Waiting for [(1, <ConsumerMessage: TopicPartition(topic='test-topic', partition=0) offset=20>)] tasks
[2019-07-29 16:48:15,106: WARNING]: [^--Consumer]: wait_empty: Waiting for [(1, <ConsumerMessage: TopicPartition(topic='test-topic', partition=0) offset=20>)] tasks
[2019-07-29 16:48:25,337: WARNING]: [^--Consumer]: wait_empty: Waiting for [(1, <ConsumerMessage: TopicPartition(topic='test-topic', partition=0) offset=20>)] tasks
[2019-07-29 16:48:35,581: WARNING]: [^--Consumer]: wait_empty: Waiting for [(1, <ConsumerMessage: TopicPartition(topic='test-topic', partition=0) offset=20>)] tasks
[2019-07-29 16:48:45,894: WARNING]: [^--Consumer]: wait_empty: Waiting for [(1, <ConsumerMessage: TopicPartition(topic='test-topic', partition=0) offset=20>)] tasks
[2019-07-29 16:48:56,143: WARNING]: [^--Consumer]: wait_empty: Waiting for [(1, <ConsumerMessage: TopicPartition(topic='test-topic', partition=0) offset=20>)] tasks
[2019-07-29 16:49:06,502: WARNING]: [^--Consumer]: wait_empty: Waiting for [(1, <ConsumerMessage: TopicPartition(topic='test-topic', partition=0) offset=20>)] tasks
```

If I remove the `filter` call, it stops properly.

# Versions

* Python version: 3.7.2
* Faust version: 1.7.4
* Operating system: macOS
* Kafka version: 2.2.1

**Comment by martinmaillard** [comment]
After playing a bit more, I found a simpler example that causes the same issue. The problem is not related to `take`.

Since filtered events are never acked, the stream waits for the next "unfiltered" event to commit the offset and allow the app to stop. With a filter that never lets events pass, the app will always hang when it receives SIGINT.
```python
@app.agent(test_topic)
async def my_agent(stream):
    async for event in stream.filter(lambda e: False):
        pass
```

**Comment by ask** [comment]
Fixed by #412 :tada:

**Comment by rucciva** [comment]
Hi, i'm encountering this problem despite using 1.10.1. Could it be a regression?

**Comment by tienlx93** [comment]
Hello.

I'm using faust 1.10.2, this problem still existed.
There is no warning log for `[^--Consumer]: wait_empty: Waiting for [(1, <ConsumerMessage: TopicPartition(topic='test-topic', partition=0) offset=20>)] tasks`

But when I check the kafka-consumer-group.sh in kafka, the offset not advancing:
![image](https://user-images.githubusercontent.com/9817634/74803329-e45d3400-52f5-11ea-96bb-86c5e72ebd08.png)

Thanks.

**Comment by zerafachris** [comment]
@ask  This is still present on 1.10.4. Any updates?

**Comment by zerafachris** [comment]
@ask @martinmaillard Any news on this?
